name: Publish Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish:
    name: Upload release to PyPI and GitHub
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write # Required for PyPI OIDC trusted publishing
      contents: write # Required to create a GitHub Release

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'

      - name: Install build tools
        run: pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
          generate_release_notes: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1